### ISSUE TITLE
run on more than one GPU

### ISSUE THREAD

**Issue by DecentMakeover** [junqiangchen/DualAttentionVNet3D#1]
Hey Thanks for sharing your work, How can i run this code on multiple GPU's?

Thanks in advance

**Comment by junqiangchen** [comment]
hi,
if want run on multiple GPU,should reimplement the code that supports your wanted.

**Comment by DecentMakeover** [comment]
@junqiangchen Hey, did you place in the Kits challenge?

**Comment by junqiangchen** [comment]
no，i don't，there are many parameters should modify carefully
